using System.Threading.Tasks;
using Tch.YumlClient.Domain.Helpers;
using Tch.YumlClient.Domain.Objects;

namespace Tch.YumlClient.Interfaces.Helpers
{
   /// <summary>
   ///    Help service that manages http communication with yuml.me
   /// </summary>
   internal interface IHttpService
   {
      /// <summary>
      ///    Send text and parse response
      /// </summary>
      /// <param name="dslText"></param>
      /// <param name="fileExtension"></param>
      /// <returns></returns>
      Task<HttpResponseVm> PostUmlText(string dslText, string fileExtension);

      /// <summary>
      ///    Download diagram generated by yuml.me
      /// </summary>
      /// <param name="fileName"></param>
      /// <returns></returns>
      Task<DiagramFile> DownloadDiagramFile(string fileName);
   }
}