namespace Tch.YumlClient.Domain.Objects
{
   /// <summary>
   /// Represents diagram file generated by https:\\yuml.me
   /// </summary>
   public class DiagramFile
   {
      /// <summary>
      /// Binary file content
      /// </summary>
      public byte[] Content { get; set; }

      /// <summary>
      /// Mime content type
      /// </summary>
      public string ContentType { get; set; }

      /// <summary>
      /// File name generated by yuml.me
      /// </summary>
      public string FileName { get; set; }
   }
}